name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "ciklum-task-api" #Must be unique in Heroku
        heroku_email: "ojedamaruny@gmail.com"
        usedocker: true
        docker_build_args: |
          NODE_ENV
          SECRET_KEY
      env:
          NODE_ENV: production
          SECRET_KEY: ${{ '9eFiD=(wGb:"g<#' }}
